from pathlib import Path
path = Path('blogapp/static/js/dashboard.js')
text = path.read_text(encoding='utf-8')
replacements = {
    '// 全局状态管理': '// Global state management',
    '// 视图切换': '// View switching',
    '// 隐藏所有视图': '// Hide all views',
    '// 显示目标视图': '// Show target view',
    '// 工厂管理功能': '// Factory management features',
    '// 加载工厂列表': '// Load factory list',
    '// 添加时间戳防止缓存': '// Add timestamp to prevent caching',
    "showError('加载工厂列表失败')": "showError('Failed to load factory list')",
    "console.error('加载工厂列表失败:'": "console.error('Failed to load factory list:'",
    '// 渲染工厂列表': '// Render factory list',
    'title="编辑工厂"': 'title="Edit factory"',
    '电压等级:': 'Voltage level:',
    '变压器容量:': 'Transformer capacity:',
    '容量电费': 'Capacity fee',
    '日用电量': 'Daily usage',
    '月工作天数': 'Monthly working days',
    ' 天</span>': ' days</span>',
    '月用电量': 'Monthly usage',
    '工作时间段:': 'Working periods:',
    '查看详情': 'View details',
    '删除': 'Delete',
    '// 工作时间段管理': '// Work period management',
    '// 存储工作时间段': '// Store work periods',
    '// 当前编辑的工厂 ID（null 表示创建新工厂）': '// Current edited factory ID (null means creating a new factory)',
    '// 添加工作时间段': '// Add work period',
    '// 验证': '// Validation',
    "showError('请选择开始和结束时间')": "showError('Please select a start and end time')",
    "showError('结束时间必须大于开始时间')": "showError('End time must be later than start time')",
    '// 检查是否重叠': '// Check for overlap',
    "showError('时间段不能重叠')": "showError('Time periods cannot overlap')",
    '// 添加时间段': '// Add time period',
    '// 重置选择器': '// Reset selectors',
    '// 渲染时间段列表': '// Render period list',
    '<div class="text-muted small">暂无工作时间段</div>': '<div class="text-muted small">No work periods added yet</div>',
    '// 显示创建工厂模态框': '// Show create factory modal',
    '新建工厂': 'New Factory',
    '创建': 'Create',
    '// 重置表单': '// Reset form',
    '// 重置工作时间段': '// Reset work periods',
    '// 编辑工厂': '// Edit factory',
    "showError('工厂不存在')": "showError('Factory not found')",
    '编辑工厂': 'Edit Factory',
    '保存': 'Save',
    '// 填充表单数据': '// Fill form data',
    '// 加载工作时间段': '// Load work periods',
    '// 创建工厂': '// Create factory',
    "showError('请至少添加一个工作时间段')": "showError('Please add at least one work period')",
    '// 验证工作时间段': '// Validate work periods',
    '// 关闭模态框': '// Close modal',
    "showSuccess('工厂创建成功')": "showSuccess('Factory created successfully')",
    "showError(data.message || '创建工厂失败')": "showError(data.message || 'Failed to create factory')",
    "console.error('创建工厂失败:'": "console.error('Failed to create factory:'",
    '// 更新工厂': '// Update factory',
    "showSuccess('工厂更新成功')": "showSuccess('Factory updated successfully')",
    "showError(data.message || '更新工厂失败')": "showError(data.message || 'Failed to update factory')",
    "console.error('更新工厂失败:'": "console.error('Failed to update factory:'",
    '// 查看工厂详情': '// View factory details',
    '// 返回工厂管理页面': '// Return to factory management page',
    '// 编辑当前工厂': '// Edit current factory',
    '// 渲染工厂详情': '// Render factory details',
    '// 基本信息': '// Basic information',
    ' 天`': ' days`',
    '// 核心数据统计': '// Key metrics',
    '// 使用队友写的 carbon_emission 属性': "// Using teammate's carbon_emission property",
    '// 节省潜力 - 调用后端API（默认省钱模式）': "// Saving potential - call backend API (default cost-saving mode)",
    '// 加载优化建议': '// Load optimization suggestions',
    '// 渲染图表': '// Render charts',
    '// 渲染成本报告': '// Render cost report',
    '// 渲染建议列表': '// Render suggestion list',
    '高影响': 'High impact',
    '中影响': 'Medium impact',
    '低影响': 'Low impact',
    '预计节省:': 'Estimated saving:',
    '元/月': 'CNY/month',
    '减排:': 'Carbon reduction:',
    '行动建议:': 'Action recommendations:',
    '// 无建议': '// No suggestions',
    '当前用电方案已经很优化了！': 'The current power plan is already well optimized!',
    "console.error('加载优化建议失败:'": "console.error('Failed to load optimization suggestions:'",
    '加载优化建议失败，请稍后重试': 'Failed to load optimization suggestions. Please try again later.',
    '// 切换优化模式（省钱/减排）': '// Switch optimization mode (cost/emissions)',
    '// 调用后端 API 获取优化数据': '// Call backend API to get optimization data',
    '// 显示节省潜力': '// Show saving potential',
    '// 显示错误或无数据': '// Show error or no data',
    '<span class="text-muted small">暂无数据</span>': '<span class="text-muted small">No data available</span>',
    'kg CO₂/月': 'kg CO₂/month',
    "console.error('获取优化数据失败:'": "console.error('Failed to get optimization data:'",
    '<span class="text-muted small">加载失败</span>': '<span class="text-muted small">Loading failed</span>',
    '// 渲染电价曲线图': '// Render price line chart',
    "console.log('渲染折线图 - 动画已启用')": "console.log('Rendering line chart - animation enabled')",
    '// 销毁旧图表': '// Destroy old chart',
    '// 设置 Canvas 透明背景': '// Set canvas transparent background',
    '// 获取价格对比数据': '// Get price comparison data',
    '代理公司价格 (含代理费)': 'Agent company price (incl. fees)',
    '电网价格': 'Grid price',
    '时段:': 'Period:',
    '电价 (元/kWh)': 'Price (CNY/kWh)',
    '时间': 'Time',
    '// 渲染能源结构饼图': '// Render energy mix doughnut chart',
    "console.log('渲染饼图 - 动画已启用')": "console.log('Rendering pie chart - animation enabled')",
    '// 计算各时段用电量': '// Calculate usage by period',
    '高峰': 'Peak',
    '平时': 'Normal',
    '低谷': 'Valley',
    '// 渲染成本报告': '// Render cost report',
    '// 计算各时段汇总（hourly_breakdown 是每日数据，需要乘以工作天数）': '// Calculate period totals (hourly_breakdown is daily data, multiply by working days)',
    '// 电能费总和（不含容量费）': '// Total energy cost (excluding capacity fee)',
    '// 计算总用电量': '// Calculate total usage',
    '时段类型': 'Period type',
    '用电量 (kWh)': 'Usage (kWh)',
    '电费 (元)': 'Cost (CNY)',
    '占比': 'Share',
    '合计': 'Total',
    "console.log('表格 HTML:'": "console.log('Table HTML:'",
    "确定要删除工厂\"${factoryName}\"吗？此操作不可恢复。": "Are you sure you want to delete factory \"${factoryName}\"? This action cannot be undone.",
    "showSuccess('工厂删除成功')": "showSuccess('Factory deleted successfully')",
    "showError(data.message || '删除工厂失败')": "showError(data.message || 'Failed to delete factory')",
    "console.error('删除工厂失败:'": "console.error('Failed to delete factory:'",
    '// 工具函数': '// Utility functions',
    '// HTML 转义': '// HTML escaping',
    '// 格式化数字': '// Format numbers',
    '// 显示成功消息': '// Show success message',
    '// 显示错误消息': '// Show error message',
    '// 显示信息消息': '// Show info message',
    '// 显示 Toast 消息': '// Show toast message',
    '// 创建 toast 容器（如果不存在）': '// Create toast container (if missing)',
    '// 创建 toast 元素': '// Create toast element',
    '// 移除 toast 元素': '// Remove toast element',
    '// 性能监测和设置': '// Performance monitoring and settings',
    '// FPS 监测': '// FPS monitor',
    '// 记录 FPS（1000ms / delta）': '// Record FPS (1000ms / delta)',
    '// 基准测试时不限制帧数，实时显示时只保留最近 60 帧': '// During benchmark, do not cap frame count; for live display keep only the latest 60 frames',
    '// 取最近 10 帧的平均值': '// Take average of last 10 frames',
    '// 打开设置面板': '// Open settings panel',
    '// 加载当前设置': '// Load current settings',
    '// 运行基准测试': '// Run benchmark',
    '// 禁用按钮': '// Disable button',
    '测试中...': 'Testing...',
    '// 隐藏之前的结果': '// Hide previous results',
    '// 保存当前 UI 模式': '// Save current UI mode',
    '// 强制切换到满血版进行测试': '// Force switch to full UI for the test',
    '// 等待 100ms 让样式生效': '// Wait 100ms for styles to take effect',
    '// 标记为基准测试模式': '// Mark as benchmark mode',
    '// 强制触发所有页面元素的悬停效果': '// Force hover effect on all page elements',
    '// 移除所有 hover': '// Remove all hover effects',
    '// 强制触发当前卡片的 hover 效果': '// Force current card hover effect',
    '// 每 0.3 秒切换一个卡片': '// Rotate to the next card every 0.3 seconds',
    '// 测试 10 秒': '// Test for 10 seconds',
    '// 停止监测和悬停效果': '// Stop monitoring and hover effects',
    '// 恢复所有卡片样式': '// Restore all card styles',
    '// 恢复原来的 UI 模式': '// Restore original UI mode',
    '// 计算平均 FPS 和最低 FPS': '// Calculate average FPS and minimum FPS',
    '// 显示结果': '// Show results',
    '// 恢复按钮': '// Restore button',
    '重新测试': 'Retest',
    '// 切换 FPS 显示': '// Toggle FPS display',
    '// 更新 FPS 显示': '// Update FPS display',
    '每 0.5 秒更新一次': 'Update every 0.5 seconds',
    '// 保存设置': '// Save settings',
    '// 保存到 localStorage': '// Save to localStorage',
    '设置已保存': 'Settings saved',
    '// 初始化': '// Initialization',
    "console.log('🚀 PeakShift Dashboard 初始化...')": "console.log('🚀 PeakShift Dashboard initializing...')",
    '显示工厂管理视图': 'Show factory management view',
    '加载保存的设置': 'Load saved settings',
    "console.log('✅ Dashboard 初始化完成')": "console.log('✅ Dashboard initialization complete')",
    'DOM 加载完成后初始化': 'Initialize after DOM loaded'
}
for old, new in replacements.items():
    text = text.replace(old, new)
path.write_text(text, encoding='utf-8')
import re
remaining = []
for i, line in enumerate(text.splitlines(), 1):
    if re.search(r'[\u4e00-\u9fff]', line):
        remaining.append((i, line))
print(f'Remaining Chinese lines: {len(remaining)}')
for i, line in remaining[:50]:
    print(f'{i}: {line}')
